### ISSUE TITLE
Create a new Logo for the Lead Management Android Project

### ISSUE THREAD

**Issue by thakurutkarsh22** [JBossOutreach/lead-management-server#25]
You are required to design a whole new logo, with shadows and nice looking guides from Material Design.
You can use Android Asset Studio for this task.

Requirements:
- choose the color of the logo wisely
- do not make it so clumsy, (simple and informative)
- do not make it too vibrant
- the logo should have PNG files for all the screen resolutions

Submission:
- create a PR on GitHub repository
- add screenshots here
- add PR link here
- follow submission guidelines

Relevant Links:
- Android Asset Studio : [https://romannurik.github.io/AndroidAssetStudio/](https://romannurik.github.io/AndroidAssetStudio/)

- Reach out to us on [Gitter channel](https://gitter.im/JBossOutreach/lead-management) or comment here if you have any doubts.

**Comment by SyamSundarKirubakaran** [comment]
@thakurutkarsh22 Kindly put up this issue on [Lead Management Android Repo](https://github.com/JBossOutreach/lead-management-android)

**Comment by thakurutkarsh22** [comment]
Yeah sorry It accidentally got mixed up
