### ISSUE TITLE
Upgrade the Gradle Dependencies - Lead Management Android

### ISSUE THREAD

**Issue by thakurutkarsh22** [JBossOutreach/lead-management-server#26]
It is required that you upgrade the gradle dependencies in the Lead Management Android App to the latest versions.

Queries:
- Reach out to us on [Gitter channel](https://gitter.im/JBossOutreach/lead-management).

Submission:
- The submission has to done by giving out a Pull Request to the [Lead Management Repository.](https://github.com/JBossOutreach/lead-management-android)
- Make sure to follow Contribution Guidelines.

**Comment by SyamSundarKirubakaran** [comment]
@thakurutkarsh22 Kindly put up this issue on [Lead Management Android Repo](https://github.com/JBossOutreach/lead-management-android). This issue is not meant to be here.

**Comment by nehagup** [comment]
@thakurutkarsh22  I'm closing the issue as it's wrongly placed. :)
