### ISSUE TITLE
Error in README.MD - Travis Icon Issue

### ISSUE THREAD

**Issue by sidhyatikku** [JBossOutreach/lead-management-server#59]
### Bug Hunt: Creating your first issue

* The Travis-CI badge in README.MD is incorrect as it is just a static image.
* To resolve this issue, I'll create a PR.
* This error was made by me in GCI17 #6 and I would like to apologize for that.
* To reproduce this issue, you may undo my PR if it gets merged.
* [Task Link](https://codein.withgoogle.com/tasks/5992665570082816/?sp-organization=5198161816584192&sp-is_beginner=False&sp-categories=5)

<img width="946" alt="screen shot 2018-10-28 at 10 52 25 pm" src="https://user-images.githubusercontent.com/33092447/47619393-2dd3af80-db04-11e8-90d6-6670c2267a73.png">

**Comment by divyanshkul** [comment]
Fixed via #60
